version: "3.9"

services:
  bot:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    entrypoint: poetry run python3 -O -m gadoneko.bot
    env_file:
      - .dev.env
    depends_on:
      - mongol
      - webpanel
    volumes:
      - ".:/pjatk"
  webpanel:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    env_file:
      - .dev.env
    depends_on:
      - mongol
    volumes:
      - ".:/pjatk"
    ports:
      - "8000:8000"
    entrypoint: poetry run python3 -m uvicorn webpanel:app --host 0.0.0.0 --reload --log-level debug
  database:
    image: mongo:latest
    network_mode: host
    ports:
      - "27017:27017"
