version: "3.9"

services:
  bot:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    entrypoint: poetry run python3 -O -m gadoneko.bot
    env_file:
      - .dev.env
    depends_on:
      - database
      - webpanel
    volumes:
      - ".:/pjatk"
  webpanel:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    env_file:
      - .dev.env
    depends_on:
      - database
    volumes:
      - ".:/pjatk"
    ports:
      - "8000:8000"
    entrypoint: poetry run python3 -m uvicorn webpanel:app --host 0.0.0.0 --reload --log-level debug
  database:
    image: mongo:latest
  database-viewer:
    image: mongo-express
    depends_on:
      - database
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://database/'
    ports:
      - "8081:8081"
