version: "3.9"

services:
  bot:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    entrypoint: poetry run python3 -O -m gadoneko.bot
    env_file:
      - .dev.env
    depends_on:
      - mongol
      - webpanel
    volumes:
      - ".:/pjatk" # binds code with runtime

  webpanel:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: base
    entrypoint: poetry run python -m uvicorn webpanel:app --host 0.0.0.0 --reload --log-level debug
    ports:
      - '8000:8000'
    env_file:
      - .dev.env
    depends_on:
      - mongol
    volumes:
      - ".:/pjatk" # binds code with runtime
      
  mongol:
    image: mongo:latest
