version: "3.9"

services:
  discordcat:
    build: .
    image: pjatk21/discordcat:latest
    entrypoint: pipenv run bot
    environment:
      MOTD: awaiting for java ITN
      MONGODB_URL: mongodb://notpjatk:notThatExample1!@mongol/
    env_file:
      - .production.env
    depends_on:
      - mongol
      - webgate
    restart: unless-stopped
  webgate:
    build: .
    image: pjatk21/discordcat:latest
    entrypoint: pipenv run webpage
    ports:
      - '9093:8000'
    environment:
      MONGODB_URL: mongodb://notpjatk:notThatExample1!@mongol:27017/
    env_file:
      - .production.env
    depends_on:
      - mongol
    restart: unless-stopped
  mongol:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: notpjatk
      MONGO_INITDB_ROOT_PASSWORD: notThatExample1!
    ports:
      - 27017:27017
    restart: unless-stopped
