version: "3.9"

services:
  bot:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: bot
    entrypoint: poetry run python3 -O -m gadoneko.bot
    env_file:
      - .dev.env
    depends_on:
      - mongol
      - webpanel

  webpanel:
    build:
      dockerfile: docker/gadoneko/Dockerfile
      target: web
    entrypoint: poetry run python -m uvicorn webpanel:app --host 0.0.0.0 --reload
    ports:
      - '9093:8000'
    env_file:
      - .dev.env
    depends_on:
      - mongol

  mongol:
    image: mongo:latest

