version: "3.9"

services:
  discordcat:
    build: .
    image: kpostekk/discordcat:latest
    entrypoint: pipenv run bot
    environment:
      MONGODB_URL: mongodb://notpjatk:notThatExample1!@mongol:27017/
    env_file:
      - .production.env
    depends_on:
      - mongol
      - webgate
    restart: always
  webgate:
    build: .
    image: kpostekk/discordcat:latest
    entrypoint: pipenv run webpage
    ports:
      - '9093:8000'
    environment:
      MONGODB_URL: mongodb://notpjatk:notThatExample1!@mongol:27017/
    env_file:
      - .production.env
    depends_on:
      - mongol
  mongol:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: notpjatk
      MONGO_INITDB_ROOT_PASSWORD: notThatExample1!
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: devel
      ME_CONFIG_MONGODB_URL: mongodb://notpjatk:notThatExample1!@mongol:27017/
