name: Docker CI

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (bot)
        uses: docker/build-push-action@v2
        with:
          file: docker/gadoneko/Dockerfile
          target: bot
          context: .
          push: true
          tags: |
            ghcr.io/pjatk21/gadoneko-bot:latest
            ghcr.io/pjatk21/gadoneko-bot:${{github.ref_name}}

      - name: Build and push (celery)
        uses: docker/build-push-action@v2
        with:
          file: docker/gadoneko/Dockerfile
          target: celery
          context: .
          push: true
          tags: |
            ghcr.io/pjatk21/gadoneko-celery:latest
            ghcr.io/pjatk21/gadoneko-celery:${{github.ref_name}}

      - name: Build and push (web)
        uses: docker/build-push-action@v2
        with:
          file: docker/gadoneko/Dockerfile
          target: web
          context: .
          push: true
          tags: |
            ghcr.io/pjatk21/gadoneko-web:latest
            ghcr.io/pjatk21/gadoneko-web:${{github.ref_name}}
